### ISSUE TITLE
Kick ENPOINT to get chat room messages

### ISSUE THREAD

**Issue by l3franc3** [MistyKnives/Kick4J#1]
Hello!

Is there any ENDPOINT or any way to get an user chat room messages?

Thanks!

**Comment by r0nn13g** [comment]
are there any end points available for kick at all? i tried "https://kick.com/api/v1" but got a 404.

**Comment by l3franc3** [comment]
As far as I know, you can use:

https://kick.com/api/v1/channels/{username}
https://kick.com/api/v1/users/{username}

to fetch some information in JSON.

But not much more than that has been publicly released

**Comment by tyyzf** [comment]
apologises for not replying, i will link a json file with all current endpoints that they have.
enjoy!

[Kick Endpoints](https://cdn.discordapp.com/attachments/1104364388317675651/1106343139406520321/kick-endpoints.json)

**Comment by r0nn13g** [comment]
no worries, Thank you !

**Comment by tyyzf** [comment]
closed, should be resolved now. feel free to email me business@mistyknives.co.uk for any future help.
