### ISSUE TITLE
Endpoint to retrieve channel info by user id ?

### ISSUE THREAD

**Issue by Lyfhael** [MistyKnives/Kick4J#2]
Hey,
Rather than through channel/user name, is it possible to retrieve informations through an id ?
Thanks!

**Comment by tyyzf** [comment]
Hello,
Sadly not yet. This will most likely be implemented once the Kick API has been properly made. This is currently using the internal api from kick. 

If you'd like to do this, you could listen to chat messages through Pusher (what kick uses to send events like messages/subs/followers/etc. Then once you start listening (you could listen to the biggest channels like xQc, etc) then save the ID and Slug of the user then search through the saved data by ID then capture the slug then search through the API. 

If you would like any help, feel free to msg me on Discord (mistyknives) no #. I'm happy to help :)
