### ISSUE TITLE
Check if a streamer is in live.

### ISSUE THREAD

**Issue by MicheleDiMezzaCutillo** [MistyKnives/Kick4J#4]
_I'm still noob in programming but I'm trying to learn slowly among other things I'm not very good with English._

Can you tell me how I make an API call that returns a JSON about a stream in Java? starting from the name?
with info like
is it live?
live title
current category or game?

**Comment by MicheleIlPro** [comment]
I managed to understand a little more, but now the problem is that .formatted() does not exist.. why?

**Comment by tyyzf** [comment]
https://kick.com/api/v2/channels/{username}/livestream - for livestream information
https://kick.com/api/v2/channels/{username} - for information such as is live, etc.
